baseURL = "https://docs.multisafepay.com/"
languageCode = "en-us"
title = "MultiSafepay Docs"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

# Enable nested shortcode
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]

[blackfriday]
hrefTargetBlank = true

#CUSTOM PARAMS
[params]
    search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"

# Menu config

[[menu.main]]
    name = "Getting started"
    url  = "/getting-started/"
    pre = "fa fa-rocket fa-lg"
    weight = 1

[[menu.main]]
    name = "Create a test account"
    url  = "/getting-started/create-a-test-account"
    parent = "Getting started"
    weight = 2

[[menu.main]]
    name = "Set up your account"
    url  = "/getting-started/set-up-your-account"
    parent = "Getting started"
    weight = 3

[[menu.main]]
    name = "Choose your integration"
    url = "/getting-started/choose-your-integration"
    parent = "Getting started"
    weight = 4

[[menu.main]]
    name = "Test your integration"
    url  = "/getting-started/test-your-integration"
    parent = "Getting started"
    weight = 5

[[menu.main]]
    name = "Onboard and go live"
    url  = "/getting-started/go-live"
    parent = "Getting started"
    weight = 6

[[menu.main]]
    name = "Glossaries"
    url  = "/getting-started/glossaries/"
    parent = "Getting started"
    weight = 7

[[menu.main]]
    name = "My account"
    url  = "/my-account/"
    pre = "fa fa-user-circle fa-lg"
    identifier = "my-account"
    weight = 10

[[menu.main]]
    name = "Creating an account"
    url  = "/account/create-account/"
    parent = "my-account"
    identifier = "create-account"
    weight = 110

[[menu.main]]
    name = "Manage my account"
    url  = "/account/manage-account/"
    parent = "my-account"
    identifier = "manage-account"
    weight = 120

[[menu.main]]
    name = "Partner and primary accounts"
    url  = "/account/partner-primary-accounts/"
    parent = "my-account"
    identifier = "partner-primary-accounts"
    weight = 130

[[menu.main]]
    name = "Onboarding and go live"
    url  = "/account/onboarding-golive/"
    parent = "my-account"
    identifier = "go-live"
    weight = 140

[[menu.main]]
    name = "Manage your balance"
    url  = "/my-account/manage-your-balance/"
    parent = "my-account"
    identifier = "manage-your-balance"
    weight = 150



[[menu.main]]
    name = "Integrations"
    url  = "/integrations/"
    pre = "fa fa-plug fa-lg"
    identifier = "integrations"
    weight = 20

[[menu.main]]
    name = "Ready-made"
    url  = "/integrations/ready-made/"
    parent = "integrations"
    identifier = "ready-made"
    weight = 210

[[menu.main]]
    name = "Partner integrations"
    url  = "/partner-integrations/"
    parent = "integrations"
    identifier = "partner-integrations"
    weight = 220

[[menu.main]]
    name = "Checkouts"
    url  = "/checkouts/"
    parent = "integrations"
    identifier = "checkouts"
    weight = 230

[[menu.main]]
    name = "Test your integration"
    url  = "/integrations/testing/"
    parent = "integrations"
    identifier = "testing"
    weight = 240

[[menu.main]]
    name = "Payments"
    url  = "/payments/"
    identifier = "payments"
    pre = "fa fa-credit-card fa-lg"
    weight = 30

[[menu.main]]
    name = "Payment methods"
    url  = "/payment-methods/"
    parent = "payments"
    identifier = "payment-methods"
    weight = 310

[[menu.main]]
    name = "About payments"
    url  = "/payments/about"
    parent = "payments"
    weight = 320

[[menu.main]]
    name = "Payment features"
    url  = "/payments/features"
    parent = "payments"
    weight = 330

[[menu.main]]
    name = "Refunds and chargebacks"
    url  = "/refunds-chargebacks/"
    parent = "payments"
    weight = 340

[[menu.main]]
    name = "Accounting"
    url  = "/accounting/"
    pre = "fa fa-calculator fa-lg"
    identifier = "accounting"
    weight = 50

[[menu.main]]
    name = "Reports"
    url  = "/accounting/reports/"
    parent = "accounting"
    identifier = "reports"
    weight = 510

[[menu.main]]
    name = "Accounting integrations"
    url  = "/accounting/integrations/"
    parent = "accounting"
    identifier = "accounting-integrations"
    weight = 520

[[menu.main]]
    name = "Reconciliation through API"
    url  = "/accounting/api-reconciliation/"
    parent = "accounting"
    identifier = "api-reconciliation"
    weight = 530

[[menu.main]]
    name = "Security and legal"
    url  = "/security-and-legal/"
    pre = "fa fa-lock fa-lg"
    identifier = "security-and-legal"
    weight = 60

[[menu.main]]
    name = "Payment regulations"
    url  = "/payment-regulations/"
    parent = "security-and-legal"
    identifier = "payment-regulations"
    weight = 610

[[menu.main]]
    name = "Risk and fraud"
    url  = "/risk-fraud/"
    parent = "security-and-legal"
    identifier = "risk-fraud"
    weight = 620

[[menu.main]]
    name = "Developer tools"
    url  = "/developer/"
    identifier = "developer"
    pre = "fa fa-cube fa-lg"
    weight = 70

[[menu.main]]
    name = "About our API"
    url  = "/developer/api/"
    parent = "developer"
    identifier = "about-api"
    weight = 710

[[menu.main]]
    name = "Wrappers and SDKs"
    url  = "/developer/wrappers/"
    parent = "developer"
    identifier = "wrappers-sdks"
    weight = 720

[[menu.main]]
    name = "Errors explained"
    url  = "/developer/errors-explained/"
    parent = "developer"
    identifier = "errors-explained"
    weight = 730

[[menu.main]]
    name = "Developer information"
    url  = "/developer/general/"
    parent = "developer"
    identifier = "developer-information"
    weight = 740

[[menu.main]]
    name = "API Reference"
    url  = "/api/"
    pre = "fa fa-code fa-lg"
    weight = 80
