# This is a workflow to automatically generate diagram SVGs 

name: Create mermaid diagrams


on:

# Run on pushes to master (includes merged PRs into master and direct pushes)
  push:
    branches: [ master, readmedocs-staging ]

  # Enable manual triggers (for testing)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Create diagram SVGs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Filter for diagram source files
        run: |
          npm install @mermaid-js/mermaid-cli

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            for diagram-file in echo "$file" | grep static/diagrams/src/; do
              npx mmdc -i $diagram-file -o static/diagrams/svg/$diagram-file --configFile static/diagrams/config.json
            done
          done

