# This is a workflow to automatically generate diagram SVGs 

name: Create mermaid diagrams


on:

# Run on pull requests into readmedocs-staging
  pull_request:
    types: [ closed ]
    branches: [ readmedocs-staging ]

  # Enable manual triggers (for testing)
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged ==  true
    runs-on: ubuntu-latest 
    name: Create diagram SVGs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file" 
          done

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Generate diagrams
        run: |
          npm install @mermaid-js/mermaid-cli

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            filename=$(basename "$file")
            fname="${filename%.*}"
            ext="${filename##*.}"
            echo "file: $file ; filename: $filename ; fname: $fname ; ext: $ext"

            if [ "$ext" = "mmd" ]
            then
              echo "$file with extension .mmd has changed"
              npx mmdc -i $file -o static/diagrams/svg/${fname}.svg --configFile static/diagrams/config.json
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate mermaid diagrams
          file_pattern: static/diagrams/svg/*