name: URL Checker
on:
#  pull_request:
#    types: [ closed ]
#    branches: [ readmedocs-staging ]
  workflow_dispatch:

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Delete branch
      run: git push --delete origin $GITHUB_REF_NAME
