name: Check Markdown links on pull request
on: [pull_request]

jobs:
  netlify-preview-check:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.wait-for-netlify-preview.outputs.url }}
    steps:
    - name: Wait for Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.3
      id: wait-for-netlify-preview
      with:
        site_name: "multisafepay-docs"
        max_timeout: 300
  markdown-link-check:
    needs: netlify-preview-check
    if: ${{ needs.netlify-preview-check.outputs.url != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Checkout source branch
      uses: actions/checkout@master
    - name: Insert deployment URL
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "DEPLOYMENT_URL"
        replace: "${{ needs.netlify-preview-check.outputs.url }}"
        regex: false
        include: '**mlc_config.json'
    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
        config-file: './.github/mlc_config.json'

