name: Check for API Spec Updates

on:
  schedule:
    # Runs at 03:00 UTC every day
    - cron: "0 3 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository to access the existing 'openapi.json'
      - name: Check out main branch
        uses: actions/checkout@v4

      # Step 2: Download the latest API spec from the URL
      - name: Download latest API spec
        run: |
          curl -f -o downloaded-openapi.json https://api.multisafepay.com/v1/json/openapi.json
          echo "Downloaded latest API spec."

      # Step 3: Install the openapi-diff tool
      - name: Install openapi-diff
        run: npm install -g openapi-diff

      # Step 4: Compare the existing spec with the new one and output the result
      # The '|| true' ensures the workflow continues even if differences are found,
      # as openapi-diff exits with a non-zero code when it finds changes.
      - name: Compare API specs
        id: api_diff
        run: |
          echo "Comparing local 'openapi.json' with the newly downloaded spec..."
          openapi-diff openapi.json downloaded-openapi.json > diff-output.txt || true

      # Step 5: Display the comparison results in the workflow log
      - name: Show difference output
        run: |
          echo "API Diff Output:"
          cat diff-output.txt