name: Readme sync docs on merge
on:
  workflow_dispatch
  # pull_request:
  #   types:
  #     - closed
    # branches: 
    #   - readmedocs-staging

jobs:
  readme-docs-sync:
    #if: github.ref == 'refs/heads/readmedocs-staging'
    #if: github.event.pull_request.merged ==  true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'readmedocs-staging'
    - uses: readmeio/rdme@7.2.0
      env:
        README: ${{ secrets.README }}
      with:
        rdme: rdme docs content --version=v1.0 --key="$README"
