name: Readme sync docs on merge
on:
  pull_request:
    types:
      - closed
    branches: 
      - master

jobs:
  readme-docs-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: readmeio/rdme@v10
        with:
          rdme: docs upload ./content --branch=v1.0
        env:
          DEBUG: rdme*
          README_API_KEY: ${{ secrets.README }}

      - uses: readmeio/rdme@v10
        with:
          rdme: reference upload ./api --branch=v1.0
        env:
          DEBUG: rdme*
          README_API_KEY: ${{ secrets.README }}
      - name: Sync API Reference to ReadMe
        uses: readmeio/rdme@v10
        with:
          rdme: openapi ./openapi/docsopenapi.yaml --key=${{ secrets.README }} --branch=v1.1
        env:
          DEBUG: rdme*