name: Readme sync docs on merge
on:
  pull_request:
    types:
      - closed
    branches: 
      - master

jobs:
  readme-docs-sync:
    if: github.event.pull_request.merged ==  true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: readmeio/rdme@v8
      with:
        rdme: docs content --version=v1.0 --key=${{ secrets.README }}
    - uses: readmeio/rdme@v8
      with:
        rdme: docs api --version=v1.0 --key=${{ secrets.README }}
