name: Readme sync docs on merge
on:
  pull_request:
    types:
      - closed
    branches: 
      - master

jobs:
  readme-docs-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DEBUG: rdme*
      README_API_KEY: ${{ secrets.README }}
    steps:
      - uses: actions/checkout@v4

      - name: Sync docs guides
        uses: readmeio/rdme@10.5.0-next.5
        with:
          rdme: docs ./content --version=v1.0

      - name: Sync API Reference guides
        uses: readmeio/rdme@10.5.0-next.5
        with:
          rdme: reference ./api --version=v1.0
          
      - name: Sync API Reference to ReadMe
        uses: readmeio/rdme@10.5.0-next.5
        with:
          rdme: openapi ./openapi/docsopenapi.yaml --key=${{ secrets.README }} --version=v1.1

