name: Check spelling on pull request
on: [pull_request]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
        
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          files: |
            content/**/*.md
            api/**/*.md
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Run spellchecker on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: rojopolis/spellcheck-github-actions@0.27.0
        with:
          # Pass the output from the 'changed-files' step directly.
          # This is the correct and most efficient way.
          source_files: ${{ steps.changed-files-specific.outputs.all_changed_files }}
          task_name: markdown